GET http://localhost:5229/products

###
GET http://localhost:5229/products/low-stock

###
POST http://localhost:5229/products
Content-Type: application/json

{
    "name": "T-shirt 1",
    "productCode": "Mens Casual Premium Slim Fit T-Shirts ",
    "initialStockCount":40,
    "criticalStockCount": 90
}
